// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOYlzdtYhJiJWwChrod8kPtazNNFtsqAE',
    appId: '1:299934911671:web:a18f177c1a6572c6929132',
    messagingSenderId: '299934911671',
    projectId: 'calmwaves-c6569',
    authDomain: 'calmwaves-c6569.firebaseapp.com',
    storageBucket: 'calmwaves-c6569.firebasestorage.app',
    measurementId: 'G-4N449SZWT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbUR11io-huK70GyLylwNoz8Xi5786QVg',
    appId: '1:299934911671:android:464c5c843422121e929132',
    messagingSenderId: '299934911671',
    projectId: 'calmwaves-c6569',
    storageBucket: 'calmwaves-c6569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBec9hgmiVadnNJcqfbiZJw9hYWXIyhvX4',
    appId: '1:299934911671:ios:9c017b535b142307929132',
    messagingSenderId: '299934911671',
    projectId: 'calmwaves-c6569',
    storageBucket: 'calmwaves-c6569.firebasestorage.app',
    iosBundleId: 'com.example.calmwavesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBec9hgmiVadnNJcqfbiZJw9hYWXIyhvX4',
    appId: '1:299934911671:ios:9c017b535b142307929132',
    messagingSenderId: '299934911671',
    projectId: 'calmwaves-c6569',
    storageBucket: 'calmwaves-c6569.firebasestorage.app',
    iosBundleId: 'com.example.calmwavesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOYlzdtYhJiJWwChrod8kPtazNNFtsqAE',
    appId: '1:299934911671:web:39f91f95e7112b2f929132',
    messagingSenderId: '299934911671',
    projectId: 'calmwaves-c6569',
    authDomain: 'calmwaves-c6569.firebaseapp.com',
    storageBucket: 'calmwaves-c6569.firebasestorage.app',
    measurementId: 'G-K1LCY6NK69',
  );
}
